continents/urls.py
from django.urls import path
from continents.views import ContinentsView

app_name = 'continents'

urlpatterns = [
    path("", ContinentsView.as_view(), name='home')
]

countries/urls.py
from django.urls import path

from countries.views import CountryDetailView, CountryDetailIDView, CountrySearchView

app_name = 'countries'

urlpatterns = [
    path('<int:pk>', CountryDetailIDView.as_view(), name='country_id'),
    path('<code>', CountryDetailView.as_view(), name='countries_code'),
    path('<search>/<query>', CountrySearchView.as_view(), name='countries_search'),
]

geographic/urls.py
from django.contrib import admin
from django.urls import path, include
#from countries.views import home
#from countries.views import HomeView
#from django.views.generic import TemplateView
from countries.views import (
    HomeView, TagsView, #CountryDetailView, CountryDetailIDView
)
from continents.views import ContinentsView

app_name = 'geographics'

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("", home)
    #path("", HomeView.as_view())
    #path("", TemplateView.as_view(template_name = 'countries/home.html'))
    path("", HomeView.as_view(), name='home'),
    path("tags", HomeView.as_view(), name='tags'),
    path("continents/", include("continents.urls", namespace="continents")),
    path('countries/', include("countries.urls", namespace="countries")),
    path('people/', include("people.urls", namespace="people")),
    #path('countries/<code>', CountryDetailView.as_view(), name='countries_code')
    ]

people/urls.py
from django.urls import path
from people.views import register

app_name = 'people'

urlpatterns = [
    path("register", register, name='register')
]

continents/models.py
from django.db import models

# Create your models here.
class Continent(models.Model):
    name = models.CharField(max_length = 255)
    translate = models.CharField(max_length = 255)
    color = models.CharField(max_length=255)

    def __str__(self):
        return self.name

countries/models.py
from django.db import models

class ActiveManager(models.Manager):
    def get_querset(self):
        return super().get_queryset().filter(active=True)

# Create your models here.
class Country(models.Model):
    CODES_CHOICES = (
        ('colombia', 'CO'),
        ('mexico', 'MX'),
        ('estadosunidos', 'USA'),
        ('argentina', 'AR'),
    )
    name = models.CharField(max_length = 255)
    code = models.CharField(max_length = 3, choices = CODES_CHOICES)
    continent = models.ForeignKey('continents.Continent', on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    active_manager = ActiveManager()
    objects = models.Manager()
    #objects = ActiveManager()

    def __str__(self):
        return self.name

people/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    first_name = models.CharField(max_length=255)
    nacionality = models.ManyToManyField('countries.Country')
    father  = models.OneToOneField('self', on_delete=models.CASCADE, null=True, related_name='children')

    def __str__(self):
        return self.first_name
    

people/forms.py
from django import forms
from countries.models import Country
from people.models import Person
from django.forms import ModelForm


class RegisterForm(forms.Form):
    first_name = forms.CharField(label='first name')
    nacionality = forms.ModelMultipleChoiceField(queryset=Country.objects.all())
    father = forms.ModelChoiceField(required=False, queryset=Person.objects.all())

class RegisterFormModel(forms.ModelForm):

    def __init__(self, fathers, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['father'].queryset = fathers

    class Meta:
        model = Person
        fields = ['first_name', 'nacionality', 'father']

continents/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class ContinentsView(TemplateView):
    template_name = 'continents/continents.html'

    def get_context_data(self, *args, **kwargs):

        america = {'name': 'America', 'color': 'yellow'}
        africa = {'name': 'Africa', 'color': 'dark'}
        europe = {'name': 'Europe', 'color': 'blue'}
        continents = [america, africa, europe]
        return {'continents': continents}

countries/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
#from django.views.generic import View
from django.views.generic import TemplateView
from countries.models import Country
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

# Create your views here.
#def home(request):
    #return HttpResponse("hello world")
   # return render(request, "countries/home.html")


#class HomeView(View):
class HomeView(TemplateView):
    template_name = 'countries/home.html'

    #def get_context_data(self, *args, **kwargs):

        #colombia = {'name': 'colombia', 'code': 'CO'}
        #usa = {'name': 'estados unidos', 'code': 'USA'}
        #mexico = {'name': 'mexico', 'code': 'MX'}

        #countries = ['Italia', 'Francia', 'Portugal' ]
        #countries2 = [colombia, usa, mexico]
        #return {'countries': countries, 'countries2': countries2}
    #def get(self, request, *args, **kwargs):
    #    return render(request, "countries/home.html")

class CountryDetailIDView(DetailView):
    template_name = 'countries/country_detail_id.html'
    model = Country

    def get_context_data(self, *args, **kwargs):
        
        #id = kwargs['id']
        #return {'id': id}
        #try:
        #    country = Country.objects.get(id=kwargs['id'])
        #except Country.DoesNotExist as e:
        #    raise Http404()
        
        get_object_or_404(Country, id=kwargs['id'])

        return {'country': country}

class CountryDetailView(TemplateView):
    template_name = 'countries/country_detail.html'

    def get_context_data(self, *args, **kwargs):
        code = kwargs['code']
        return {'code': code}


class TagsView(TemplateView):
    template_name = 'countries/tags.html'


class CountrySearchView(ListView):
    template_name = 'countries/search.html'
    model = Country

    def get_queryet(self):
        query = self.kwargs['query']
        #return Country.objects.filter(name='Colombia')
        #return Country.objects.filter(name__startswith='co')
        #return Country.objets.filter(continent__name='Europe')
        #return Country.objets.filter(continent__name__contains='a')
        return Country.objets.filter(name__contains=query)

people/views.py
from django.shortcuts import render
from django.http import JsonResponse
from people.forms import RegisterFormModel
from people.models import Person

def register(request):
    fathers = Person.objects.filter(children__isnull=True)
    form = RegisterFormModel(fathers, request.POST or None)

    if form.is_valid():
        person = form.save()
        return JsonResponse(
            {
                'name': person.first_name,
                'father': str(person.father),
                'nacionality': ','.join([str(country) for country in person.nacionality.all() ])
            }
        )
    return render(request, "people/register.html", {'form': form})

continents/templates/continents/continent.html
<div>
    <h2 style="color: {{continent.color}}">{{continent.name}}</h2>
</div>

continents/templates/continents/continents.html
{% extends 'countries/base.html' %}

{% block content %}
<h1>Continents</h1>
{% for continent in continents %}
    {% include 'continents/continent.html'%}
{% endfor %}
{% endblock %}

countries/templates/countries/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Título default{% endblock %}</title>
        <style media="screen">
            div.a{
                background-color: lightblue;
            }
        </style>
    </head>
    <body>
        <div class="{% if request.session.testab == "a" %}a{% endif %}">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

countries/templates/countries/country.html
<h1>name: {{country.name|title}}</h1>
<p>code: {{country.code}}</p>

{% if country.name == 'colombia'  %}
    <p>yeah: {{country.code}}</p>
{% endif %}

<p>detail_id <a href="{% url "countries:country_id" id=country.id %}">Ir a detalle</a></p>
<p>detail_url <a href="{{country.detail_url}}">Ir a detalle</a></p>
<br>

countries/templates/countries/country_detail.html
{% extends 'countries/base.html'%}
{% block content %}

{% for country in countries %}
  {% if country.code == code %}
    {% include 'countries/country.html' %}
  {% endif %}

{% endfor %}
{% endblock %}

countries/templates/countries/country_detail_id.html
{% extends 'countries/base.html'%}

{% block content %}
    {% include 'countries/country.html' with country=object %}
{% endblock %}

countries/templates/countries/home.html
{% extends 'countries/base.html' %}

{% block title %} Hello World {% endblock %}

{% block content %}
    <h1>Hello World</h1>
    <ul>
        <li><a href="{% url "tags" %}">Tags</a></li>
        <li><a href="{% url "continents:home" %}">Continents</a></li>
        <li><a href="{% url "countries:country_id" id=1 %}">Country Detail</a></li>
    </ul>

    {% for country in countries %}
        <p>{{country}}</p>
    {% endfor %}
    <hr>

    
{% endblock %}

countries/templates/countries/search.html
{% extends 'countries/base.html'%}

{% block content %}
    {% for country in object_list %}
        {% include "countries/country.html" %}
    {% endfor %}
{% endblock %}

countries/templates/countries/tags.html
{% extends 'countries/base.html' %}

{% block content %}
    <h1>Hello World</h1>

    {% include countries/country.html %}
{% endblock%}

people/templates/people/register.html
{% extends 'countries/base.html' %}

{% block title %}Register{% endblock%}

{% block content %}
    <form action="." method="post">
        {{form}}
        {% csrf_token %}
        <input type="submit" name="" value="Registro">
    </form>
{% endblock %}